variable "location" {
  description = "Azure region"
  type        = string
  default     = "westeurope"
}

variable "image_tag" {
  description = "Docker image tag to deploy — injected by CI"
  type        = string
}

variable "ecr_registry" {
  description = "AWS ECR registry hostname (e.g. 123456789.dkr.ecr.us-east-1.amazonaws.com)"
  type        = string
}

variable "ecr_password" {
  description = "ECR auth token — generated by CI with: aws ecr get-login-password"
  type        = string
  sensitive   = true
}

variable "pause_deploy" {
  description = "Emergency toggle — prevents deploys when set to true"
  type        = bool
  default     = false
}
